[package]
name = "luma-nn"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
description = "neural network"
keywords = { workspace = true }
license = { workspace = true }

[features]
cuda = ["dep:luma-cuda"]

[dependencies]
luma-tensor = { workspace = true }
luma-cuda = { workspace = true, optional = true }
luma-macros = { workspace = true }
luma-io = { workspace = true }
thiserror = { workspace = true }
thiserrorctx = { workspace = true }

[dev-dependencies]
luma-cpu = { workspace = true }
