[package]
name = "luma-ml"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
description = "machine learning"
keywords = { workspace = true }
license = { workspace = true }

[features]
cuda = ["luma-tensor/cuda"]

[dependencies]
luma-tensor = { workspace = true }
thiserror = { workspace = true }
thiserrorctx = { workspace = true }
derive_builder = { workspace = true }