[workspace]
members = [
    "luma-tensor",
    "luma-cuda-kernel",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
repository = "https://github.com/MoleSir/luma.git"
description = "A tiny ML framework"
keywords = ["machine-learning", "auto-grad"]
license = "MIT"

[workspace.dependencies]
luma-tensor = { path = "./luma-tensor", package = "luma-tensor", version = "0.0.1" }
luma-cuda-kernel = { path = "./luma-cuda-kernel", package = "luma-cuda-kernel", version = "0.0.1" }

thiserror = "2.0"
rand = "0.9.2"
rand_distr = "0.5.1"
gemm = "0.19"
libm = "0.2.15"
num_cpus = "1.17"
paste = "1.0.15"
cudarc = "0.19.8"