[package]
name = "luma-tensor"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
description = "tensor crate with autograd"
keywords = { workspace = true }
license = { workspace = true }

[features]
default = []
cuda = ["dep:cudarc", "dep:luma-cuda-kernel"]

[dependencies]
luma-cuda-kernel = { workspace = true, optional = true }
thiserror =  { workspace = true }
rand =  { workspace = true }
rand_distr =  { workspace = true }
gemm =  { workspace = true }
libm =  { workspace = true }
num_cpus =  { workspace = true }
paste =  { workspace = true }
bytemuck = { workspace = true }
cudarc = { workspace = true, optional = true, features = ["cuda-version-from-build-system", "driver", "nvrtc", "cublas"] }
