use std::path::{Path, PathBuf};
use std::process::Command;

/// Pure-C stub implementing the flash-attention C ABI. Used when no usable
/// `nvcc` is found so the crate still compiles/links; every entry point reports
/// `FLASH_ATTN_ERR_CUDA` at runtime.
const STUB_SRC: &str = r#"
/* Auto-generated by luma-flash-attn/build.rs: built without nvcc. */
#define FLASH_ATTN_ERR_CUDA 5

static _Thread_local char g_last_error[] =
    "luma-flash-attn was built without CUDA (nvcc not found); GPU support is disabled";

const char* flash_attn_last_error(void) { return g_last_error; }

#define BATCH(NAME)                                                                     \
    int NAME(const void* a, const void* b, const void* c, void* d,                      \
             int e, int f, int g, int h, int i, int j, int k, float l,                  \
             const void* m, void* n) { return FLASH_ATTN_ERR_CUDA; }

#define VARLEN(NAME)                                                                    \
    int NAME(const void* a, const void* b, const void* c, void* d,                      \
             const void* e, const void* f, const void* g,                               \
             int h, int i, int j, int k, int l, int m, int n, int o, int p, int q,      \
             float r, void* s) { return FLASH_ATTN_ERR_CUDA; }

#define KVCACHE(NAME)                                                                   \
    int NAME(const void* a, const void* b, const void* c, void* d,                      \
             const void* e, const void* f,                                              \
             int g, int h, int i, int j, int k, int l, float m, void* n) {              \
        return FLASH_ATTN_ERR_CUDA;                                                     \
    }

BATCH(flash_attn_f32)
BATCH(flash_attn_f16)
BATCH(flash_attn_bf16)
VARLEN(flash_attn_varlen_f32)
VARLEN(flash_attn_varlen_f16)
VARLEN(flash_attn_varlen_bf16)
KVCACHE(flash_attn_with_kvcache_f32)
KVCACHE(flash_attn_with_kvcache_f16)
KVCACHE(flash_attn_with_kvcache_bf16)
"#;

/// Locate a usable `nvcc`. Env roots are only trusted if `<root>/bin/nvcc`
/// actually exists; otherwise fall back to `which nvcc`.
fn find_nvcc() -> Option<PathBuf> {
    for var in ["CUDA_HOME", "CUDA_PATH", "CUDA_ROOT"] {
        if let Ok(v) = std::env::var(var)
            && !v.is_empty()
        {
            let p = PathBuf::from(&v).join("bin").join("nvcc");
            if p.is_file() {
                return Some(p);
            }
        }
    }
    let out = Command::new("which").arg("nvcc").output().ok()?;
    if !out.status.success() {
        return None;
    }
    let nvcc = PathBuf::from(String::from_utf8_lossy(&out.stdout).trim());
    nvcc.is_file().then_some(nvcc)
}

/// CUDA arch to compile for. `CUDA_ARCH` (e.g. `90`, `80`) wins; otherwise
/// detect every GPU on the machine via `nvidia-smi`; otherwise fall back to
/// nvcc's default. Emits SASS (`code=sm_XX`) + PTX (`code=compute_XX`).
fn cuda_arch_flags() -> Vec<String> {
    if let Ok(a) = std::env::var("CUDA_ARCH") {
        let a = a.trim();
        if !a.is_empty() {
            return vec![
                format!("-gencode=arch=compute_{a},code=sm_{a}"),
                format!("-gencode=arch=compute_{a},code=compute_{a}"),
            ];
        }
    }

    let Ok(out) = Command::new("nvidia-smi")
        .args(["--query-gpu=compute_cap", "--format=csv,noheader"])
        .output()
    else {
        return Vec::new();
    };
    if !out.status.success() {
        return Vec::new();
    }

    let mut seen = std::collections::BTreeSet::new();
    let mut flags = Vec::new();
    for line in String::from_utf8_lossy(&out.stdout).lines() {
        let num: String = line.trim().chars().filter(|c| c.is_ascii_digit()).collect();
        if num.is_empty() || !seen.insert(num.clone()) {
            continue;
        }
        flags.push(format!("-gencode=arch=compute_{num},code=sm_{num}"));
        flags.push(format!("-gencode=arch=compute_{num},code=compute_{num}"));
    }
    flags
}

/// Every `kernels/*.cu` is compiled into one archive; each translation unit
/// defines exactly one `extern "C"` entry point (plus the shared getter).
fn kernel_sources() -> Vec<PathBuf> {
    let dir = Path::new("kernels");
    println!("cargo:rerun-if-changed={}", dir.display());
    let mut sources: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", dir.display()))
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|ext| ext == "cu"))
        .collect();
    sources.sort();
    assert!(!sources.is_empty(), "no kernels/*.cu found");
    for src in &sources {
        println!("cargo:rerun-if-changed={}", src.display());
    }
    sources
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=CUDA_HOME");
    println!("cargo:rerun-if-env-changed=CUDA_PATH");
    println!("cargo:rerun-if-env-changed=CUDA_ROOT");
    println!("cargo:rerun-if-env-changed=CUDA_ARCH");
    println!("cargo:rerun-if-env-changed=CC");
    println!("cargo:rerun-if-env-changed=FLASH_ATTN_FORCE_STUB");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let force_stub = std::env::var("FLASH_ATTN_FORCE_STUB").is_ok_and(|v| !v.is_empty());

    match (force_stub, find_nvcc()) {
        (false, Some(nvcc)) => build_with_nvcc(&nvcc, &out_dir),
        (true, _) => {
            println!("cargo:warning=luma-flash-attn: FLASH_ATTN_FORCE_STUB set, building stub");
            build_stub(&out_dir);
        }
        (false, None) => {
            println!(
                "cargo:warning=luma-flash-attn: nvcc not found, building stub (GPU support disabled)"
            );
            build_stub(&out_dir);
        }
    }

    println!("cargo:rustc-link-search={}", out_dir.display());
    println!("cargo:rustc-link-lib=static=flash_attn");
}

/// Real build: compile every `kernels/*.cu` with nvcc, archive, and link cudart.
fn build_with_nvcc(nvcc: &Path, out_dir: &Path) {
    let root = nvcc.parent().and_then(Path::parent);

    let arch = cuda_arch_flags();
    let mut objects: Vec<PathBuf> = Vec::new();

    for src in kernel_sources() {
        let stem = src.file_stem().unwrap().to_string_lossy();
        let obj = out_dir.join(format!("{stem}.o"));
        let mut args: Vec<String> = [
            "-c",
            src.to_str().unwrap(),
            "-o",
            obj.to_str().unwrap(),
            "-std=c++17",
            "-O3",
            "-Xcompiler",
            "-fPIC",
            "--use_fast_math",
            "-I",
            "kernels",
        ]
        .iter()
        .map(|s| s.to_string())
        .collect();
        args.extend(arch.iter().cloned());

        let out = Command::new(nvcc)
            .args(&args)
            .output()
            .expect("failed to run nvcc");
        assert!(
            out.status.success(),
            "nvcc failed for {}:\n{}",
            src.display(),
            String::from_utf8_lossy(&out.stderr)
        );
        objects.push(obj);
    }

    archive(out_dir, &objects);

    println!("cargo:rustc-link-lib=dylib=cudart");
    println!("cargo:rustc-link-lib=dylib=stdc++");

    // cudart 的库目录（否则二进制链接 / 运行都找不到 -lcudart）。nvcc 所在
    // CUDA 发行版的 lib64 优先，避免和系统里其它版本的 cudart 混用。
    if let Some(root) = root {
        for sub in ["lib64", "lib", "targets/x86_64-linux/lib"] {
            let dir = root.join(sub);
            if dir.is_dir() {
                println!("cargo:rustc-link-search=native={}", dir.display());
                println!("cargo:rustc-link-arg=-Wl,-rpath,{}", dir.display());
            }
        }
    }
}

/// Fallback build: compile the pure-C stub with the system C compiler.
fn build_stub(out_dir: &Path) {
    let cc = std::env::var("CC").unwrap_or_else(|_| "cc".into());

    let src = out_dir.join("flash_attn_stub.c");
    std::fs::write(&src, STUB_SRC).expect("failed to write stub source");
    let obj = out_dir.join("flash_attn_stub.o");

    let out = Command::new(&cc)
        .args([
            "-c",
            src.to_str().unwrap(),
            "-o",
            obj.to_str().unwrap(),
            "-O2",
            "-fPIC",
            "-w",
        ])
        .output()
        .unwrap_or_else(|e| panic!("failed to run C compiler `{cc}` for stub: {e}"));
    assert!(
        out.status.success(),
        "C compiler `{cc}` failed building stub:\n{}",
        String::from_utf8_lossy(&out.stderr)
    );

    archive(out_dir, std::slice::from_ref(&obj));
}

fn archive(out_dir: &Path, objects: &[PathBuf]) {
    let lib = out_dir.join("libflash_attn.a");
    let _ = std::fs::remove_file(&lib);
    let mut ar_args: Vec<String> = vec!["rcs".into(), lib.to_str().unwrap().into()];
    ar_args.extend(objects.iter().map(|o| o.to_str().unwrap().to_string()));
    let out = Command::new("ar")
        .args(&ar_args)
        .output()
        .expect("failed to run ar");
    assert!(
        out.status.success(),
        "ar failed:\n{}",
        String::from_utf8_lossy(&out.stderr)
    );
}
